modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/KeMoonoDev/Unloaded-Activity/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "unloadedactivity"
version = "${version}"
displayName = "Unloaded Activity"
authors = "Moono"
description = "Simulates blocks and entities to catch up after being unloaded for a period of time."
logoFile = "icon.png"

[[dependencies.unloadedactivity]]
modId = "neoforge"
type = "required"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "unloadedactivity.mixins.json"
[[mixins]]
config = "unloadedactivityneoforge.mixins.json"

[[dependencies.unloadedactivity]]
modId = "minecraft"
type = "required"
mandatory = true
versionRange = "${compatible_versions_neo_or_forge}"
ordering = "NONE"
side = "SERVER"

["lithium:options"]
"world.block_entity_ticking.sleeping.furnace" = false

["unloadedactivity:options"]
disable_compat = ["examplemod"]